### ISSUE TITLE
Why is entropy confidence negative?

### ISSUE THREAD

**Issue by greatwallet** [yd-yin/FisherMatch#2]
Hi! Thank you for your inspiring work!

I noticed that the entropy threshold $\tau$ is set to -5.3. Why is it negative? Shouldn't entropy always positive?

**Comment by yd-yin** [comment]
Hi! Thanks for your interest.

We are computing the entropy of a continuous variable, which is also called [differential entropy](https://en.wikipedia.org/wiki/Differential_entropy) (微分熵). Different from the entropy of discrete variables, differential entropy of continuous variables can be negative.


If you are interested in the derivation, we can discretize a continuous variable to $n$ bins and the probability of $i$ th bin is $p(i)\Delta$, then the discrete entropy is 

$$
\begin{align}
H(X) &= -\sum_{i=1}^{n}p(x_i)\Delta \log[p(x_i)\Delta] \\
&= -\sum_{i=1}^{n}p(x_i)\Delta\log p(x_i) - \sum_{i=1}^{n}p(x_i)\Delta\log \Delta
\end{align}
$$

When $n\rightarrow \infty$, the second term can be infinity. So differential entropy only reserve the first term and finally,
$$h(X) = -\int p(x)\log p(x) \text{d}x$$

**Comment by greatwallet** [comment]
Understood. Thank you for your reply!
