### ISSUE TITLE
Why not filter by the negative log-likelihood?

### ISSUE THREAD

**Issue by NatureGeorge** [yd-yin/FisherMatch#3]
Hi, nice to see your interesting work. But I am curious about the entropy-based filtering part.
There seems to be a strong correlation between the Fisher entropy [equation 9] $H(A)$ and the negative log-likelihood of the mode w.r.t. its parameter: $-\log (p(R^{\text{mode}}|A))$, where $R^{\text{mode}}=\text{procrustes}(A)$. The negative log-likelihood can also show the prediction confidence. So why not perform filtering by the likelihood?

**Comment by yd-yin** [comment]
Hi, thanks for your interest in our work!

There could be multiple ways to represent the "confidence" of a distribution. Intuitively, entropy is an overall property of a distribution considering every point in the domain, and it well indicates the performance of predictions in our experiments. We found [Deep Bingham Network](https://arxiv.org/abs/2012.11002) also leveraging entropy as the uncertainty measure.

PDF of the mode may also be fine, but we did not try it. Note that for matrix Fisher distribution, the PDF of mode is not equivalent to its entropy, though they might be the same for some other distributions.

**Comment by NatureGeorge** [comment]
Thanks for your reply. It is true that measures like entropy describing the overall properties of the distribution are better for the confidence measurement.

EDIT: But for a unimodal distribution, the likelihood of the mode seems adequate for the task.
